In [1]:
import pandas as pd 
import json

In [2]:
df = pd.read_csv('games.csv')

In [3]:
df.head(10)

,gameId,creationTime,gameDuration,seasonId,winner,firstBlood,firstTower,firstInhibitor,firstBaron,firstDragon,...,t2_towerKills,t2_inhibitorKills,t2_baronKills,t2_dragonKills,t2_riftHeraldKills,t2_ban1,t2_ban2,t2_ban3,t2_ban4,t2_ban5
0,3326086514,1504279457970,1949,9,1,2,1,1,1,1,...,5,0,0,1,1,114,67,43,16,51
1,3229566029,1497848803862,1851,9,1,1,1,1,0,1,...,2,0,0,0,0,11,67,238,51,420
2,3327363504,1504360103310,1493,9,1,2,1,1,1,2,...,2,0,0,1,0,157,238,121,57,28
3,3326856598,1504348503996,1758,9,1,1,1,1,1,1,...,0,0,0,0,0,164,18,141,40,51
4,3330080762,1504554410899,2094,9,1,2,1,1,1,1,...,3,0,0,1,0,86,11,201,122,18
5,3287435705,1501667992132,2059,9,1,2,2,1,1,2,...,6,0,0,3,0,119,134,154,63,31
6,3314215542,1503430065724,1993,9,1,1,2,1,1,1,...,2,0,0,0,0,75,42,31,40,429
7,3329224025,1504472363684,1334,9,1,1,1,0,0,2,...,0,0,0,2,0,157,38,122,40,238
8,3318040883,1503686577549,1387,9,2,2,2,2,0,2,...,8,1,0,2,1,28,51,53,157,40
9,3327786881,1504385918871,2681,9,2,2,2,2,2,2,...,8,3,1,2,0,64,141,84,67,53

as you can see, we got all the information about games. first tower, first drogon, banned champs etc..

In [4]:
df.columns

Index(['gameId', 'creationTime', 'gameDuration', 'seasonId', 'winner',
       'firstBlood', 'firstTower', 'firstInhibitor', 'firstBaron',
       'firstDragon', 'firstRiftHerald', 't1_champ1id', 't1_champ1_sum1',
       't1_champ1_sum2', 't1_champ2id', 't1_champ2_sum1', 't1_champ2_sum2',
       't1_champ3id', 't1_champ3_sum1', 't1_champ3_sum2', 't1_champ4id',
       't1_champ4_sum1', 't1_champ4_sum2', 't1_champ5id', 't1_champ5_sum1',
       't1_champ5_sum2', 't1_towerKills', 't1_inhibitorKills', 't1_baronKills',
       't1_dragonKills', 't1_riftHeraldKills', 't1_ban1', 't1_ban2', 't1_ban3',
       't1_ban4', 't1_ban5', 't2_champ1id', 't2_champ1_sum1', 't2_champ1_sum2',
       't2_champ2id', 't2_champ2_sum1', 't2_champ2_sum2', 't2_champ3id',
       't2_champ3_sum1', 't2_champ3_sum2', 't2_champ4id', 't2_champ4_sum1',
       't2_champ4_sum2', 't2_champ5id', 't2_champ5_sum1', 't2_champ5_sum2',
       't2_towerKills', 't2_inhibitorKills', 't2_baronKills', 't2_dragonKills',
       't2_riftHeraldKills', 't2_ban1', 't2_ban2', 't2_ban3', 't2_ban4',
       't2_ban5'],
      dtype='object')

some columns are unnecessary like gameDuration or seasonId. 

but some columns are relevant each other. 

our main target is the winner of the game.

now we'll clean our data.

In [5]:
df[['t1_champ1id', 't1_champ2id']]

       t1_champ1id  t1_champ2id
0                8          432
1              119           39
2               18          141
3               57           63
4               19           29
...            ...          ...
51485           19          429
51486           90           32
51487          141           18
51488          121          236
51489           89            1

[51490 rows x 2 columns]

these id's are just id's. they are not some particular values. we need to change them into diff versions. 

only the picked champs are will be 1, others 0 for each game.

In [6]:
champ_data = json.load(open('champion_info.json'))

In [7]:
champ_data

{'type': 'champion',
 'version': '7.17.2',
 'data': {'1': {'title': 'the Dark Child',
   'id': 1,
   'key': 'Annie',
   'name': 'Annie'},
  '2': {'title': 'the Berserker', 'id': 2, 'key': 'Olaf', 'name': 'Olaf'},
  '3': {'title': 'the Colossus', 'id': 3, 'key': 'Galio', 'name': 'Galio'},
  '4': {'title': 'the Card Master',
   'id': 4,
   'key': 'TwistedFate',
   'name': 'Twisted Fate'},
  '5': {'title': 'the Seneschal of Demacia',
   'id': 5,
   'key': 'XinZhao',
   'name': 'Xin Zhao'},
  '6': {'title': 'the Dreadnought', 'id': 6, 'key': 'Urgot', 'name': 'Urgot'},
  '7': {'title': 'the Deceiver', 'id': 7, 'key': 'Leblanc', 'name': 'LeBlanc'},
  '8': {'title': 'the Crimson Reaper',
   'id': 8,
   'key': 'Vladimir',
   'name': 'Vladimir'},
  '9': {'title': 'the Harbinger of Doom',
   'id': 9,
   'key': 'Fiddlesticks',
   'name': 'Fiddlesticks'},
  '10': {'title': 'The Judicator', 'id': 10, 'key': 'Kayle', 'name': 'Kayle'},
  '11': {'title': 'the Wuju Bladesman',
   'id': 11,
   'key': 'MasterYi',
   'name': 'Master Yi'},
  '12': {'title': 'the Minotaur',
   'id': 12,
   'key': 'Alistar',
   'name': 'Alistar'},
  '13': {'title': 'the Rune Mage', 'id': 13, 'key': 'Ryze', 'name': 'Ryze'},
  '14': {'title': 'The Undead Juggernaut',
   'id': 14,
   'key': 'Sion',
   'name': 'Sion'},
  '15': {'title': 'the Battle Mistress',
   'id': 15,
   'key': 'Sivir',
   'name': 'Sivir'},
  '16': {'title': 'the Starchild',
   'id': 16,
   'key': 'Soraka',
   'name': 'Soraka'},
  '17': {'title': 'the Swift Scout',
   'id': 17,
   'key': 'Teemo',
   'name': 'Teemo'},
  '18': {'title': 'the Yordle Gunner',
   'id': 18,
   'key': 'Tristana',
   'name': 'Tristana'},
  '19': {'title': 'the Uncaged Wrath of Zaun',
   'id': 19,
   'key': 'Warwick',
   'name': 'Warwick'},
  '20': {'title': 'the Yeti Rider', 'id': 20, 'key': 'Nunu', 'name': 'Nunu'},
  '21': {'title': 'the Bounty Hunter',
   'id': 21,
   'key': 'MissFortune',
   'name': 'Miss Fortune'},
  '22': {'title': 'the Frost Archer', 'id': 22, 'key': 'Ashe', 'name': 'Ashe'},
  '23': {'title': 'the Barbarian King',
   'id': 23,
   'key': 'Tryndamere',
   'name': 'Tryndamere'},
  '24': {'title': 'Grandmaster at Arms',
   'id': 24,
   'key': 'Jax',
   'name': 'Jax'},
  '25': {'title': 'Fallen Angel',
   'id': 25,
   'key': 'Morgana',
   'name': 'Morgana'},
  '26': {'title': 'the Chronokeeper',
   'id': 26,
   'key': 'Zilean',
   'name': 'Zilean'},
  '27': {'title': 'the Mad Chemist',
   'id': 27,
   'key': 'Singed',
   'name': 'Singed'},
  '28': {'title': 'the Widowmaker',
   'id': 28,
   'key': 'Evelynn',
   'name': 'Evelynn'},
  '29': {'title': 'the Plague Rat',
   'id': 29,
   'key': 'Twitch',
   'name': 'Twitch'},
  '30': {'title': 'the Deathsinger',
   'id': 30,
   'key': 'Karthus',
   'name': 'Karthus'},
  '31': {'title': 'the Terror of the Void',
   'id': 31,
   'key': 'Chogath',
   'name': "Cho'Gath"},
  '32': {'title': 'the Sad Mummy', 'id': 32, 'key': 'Amumu', 'name': 'Amumu'},
  '33': {'title': 'the Armordillo',
   'id': 33,
   'key': 'Rammus',
   'name': 'Rammus'},
  '34': {'title': 'the Cryophoenix',
   'id': 34,
   'key': 'Anivia',
   'name': 'Anivia'},
  '35': {'title': 'the Demon Jester',
   'id': 35,
   'key': 'Shaco',
   'name': 'Shaco'},
  '36': {'title': 'the Madman of Zaun',
   'id': 36,
   'key': 'DrMundo',
   'name': 'Dr. Mundo'},
  '37': {'title': 'Maven of the Strings',
   'id': 37,
   'key': 'Sona',
   'name': 'Sona'},
  '38': {'title': 'the Void Walker',
   'id': 38,
   'key': 'Kassadin',
   'name': 'Kassadin'},
  '39': {'title': 'the Will of the Blades',
   'id': 39,
   'key': 'Irelia',
   'name': 'Irelia'},
  '40': {'title': "the Storm's Fury",
   'id': 40,
   'key': 'Janna',
   'name': 'Janna'},
  '41': {'title': 'the Saltwater Scourge',
   'id': 41,
   'key': 'Gangplank',
   'name': 'Gangplank'},
  '42': {'title': 'the Daring Bombardier',
   'id': 42,
   'key': 'Corki',
   'name': 'Corki'},
  '43': {'title': 'the Enlightened One',
   'id': 43,
   'key': 'Karma',
   'name': 'Karma'},
  '44': {'title': 'the Shield of Valoran',
   'id': 44,
   'key': 'Taric',
   'name': 'Taric'},
  '45': {'title': 'the Tiny Master of Evil',
   'id': 45,
   'key': 'Veigar',
   'name': 'Veigar'},
  '48': {'title': 'the Troll King',
   'id': 48,
   'key': 'Trundle',
   'name': 'Trundle'},
  '50': {'title': 'the Master Tactician',
   'id': 50,
   'key': 'Swain',
   'name': 'Swain'},
  '51': {'title': 'the Sheriff of Piltover',
   'id': 51,
   'key': 'Caitlyn',
   'name': 'Caitlyn'},
  '53': {'title': 'the Great Steam Golem',
   'id': 53,
   'key': 'Blitzcrank',
   'name': 'Blitzcrank'},
  '54': {'title': 'Shard of the Monolith',
   'id': 54,
   'key': 'Malphite',
   'name': 'Malphite'},
  '55': {'title': 'the Sinister Blade',
   'id': 55,
   'key': 'Katarina',
   'name': 'Katarina'},
  '56': {'title': 'the Eternal Nightmare',
   'id': 56,
   'key': 'Nocturne',
   'name': 'Nocturne'},
  '57': {'title': 'the Twisted Treant',
   'id': 57,
   'key': 'Maokai',
   'name': 'Maokai'},
  '58': {'title': 'the Butcher of the Sands',
   'id': 58,
   'key': 'Renekton',
   'name': 'Renekton'},
  '59': {'title': 'the Exemplar of Demacia',
   'id': 59,
   'key': 'JarvanIV',
   'name': 'Jarvan IV'},
  '60': {'title': 'the Spider Queen',
   'id': 60,
   'key': 'Elise',
   'name': 'Elise'},
  '61': {'title': 'the Lady of Clockwork',
   'id': 61,
   'key': 'Orianna',
   'name': 'Orianna'},
  '62': {'title': 'the Monkey King',
   'id': 62,
   'key': 'MonkeyKing',
   'name': 'Wukong'},
  '63': {'title': 'the Burning Vengeance',
   'id': 63,
   'key': 'Brand',
   'name': 'Brand'},
  '64': {'title': 'the Blind Monk',
   'id': 64,
   'key': 'LeeSin',
   'name': 'Lee Sin'},
  '67': {'title': 'the Night Hunter',
   'id': 67,
   'key': 'Vayne',
   'name': 'Vayne'},
  '68': {'title': 'the Mechanized Menace',
   'id': 68,
   'key': 'Rumble',
   'name': 'Rumble'},
  '69': {'title': "the Serpent's Embrace",
   'id': 69,
   'key': 'Cassiopeia',
   'name': 'Cassiopeia'},
  '72': {'title': 'the Crystal Vanguard',
   'id': 72,
   'key': 'Skarner',
   'name': 'Skarner'},
  '74': {'title': 'the Revered Inventor',
   'id': 74,
   'key': 'Heimerdinger',
   'name': 'Heimerdinger'},
  '75': {'title': 'the Curator of the Sands',
   'id': 75,
   'key': 'Nasus',
   'name': 'Nasus'},
  '76': {'title': 'the Bestial Huntress',
   'id': 76,
   'key': 'Nidalee',
   'name': 'Nidalee'},
  '77': {'title': 'the Spirit Walker',
   'id': 77,
   'key': 'Udyr',
   'name': 'Udyr'},
  '78': {'title': 'Keeper of the Hammer',
   'id': 78,
   'key': 'Poppy',
   'name': 'Poppy'},
  '79': {'title': 'the Rabble Rouser',
   'id': 79,
   'key': 'Gragas',
   'name': 'Gragas'},
  '80': {'title': 'the Artisan of War',
   'id': 80,
   'key': 'Pantheon',
   'name': 'Pantheon'},
  '81': {'title': 'the Prodigal Explorer',
   'id': 81,
   'key': 'Ezreal',
   'name': 'Ezreal'},
  '82': {'title': 'the Iron Revenant',
   'id': 82,
   'key': 'Mordekaiser',
   'name': 'Mordekaiser'},
  '83': {'title': 'Shepherd of Souls',
   'id': 83,
   'key': 'Yorick',
   'name': 'Yorick'},
  '84': {'title': 'the Fist of Shadow',
   'id': 84,
   'key': 'Akali',
   'name': 'Akali'},
  '85': {'title': 'the Heart of the Tempest',
   'id': 85,
   'key': 'Kennen',
   'name': 'Kennen'},
  '86': {'title': 'The Might of Demacia',
   'id': 86,
   'key': 'Garen',
   'name': 'Garen'},
  '89': {'title': 'the Radiant Dawn',
   'id': 89,
   'key': 'Leona',
   'name': 'Leona'},
  '90': {'title': 'the Prophet of the Void',
   'id': 90,
   'key': 'Malzahar',
   'name': 'Malzahar'},
  '91': {'title': "the Blade's Shadow",
   'id': 91,
   'key': 'Talon',
   'name': 'Talon'},
  '92': {'title': 'the Exile', 'id': 92, 'key': 'Riven', 'name': 'Riven'},
  '96': {'title': 'the Mouth of the Abyss',
   'id': 96,
   'key': 'KogMaw',
   'name': "Kog'Maw"},
  '98': {'title': 'the Eye of Twilight',
   'id': 98,
   'key': 'Shen',
   'name': 'Shen'},
  '99': {'title': 'the Lady of Luminosity',
   'id': 99,
   'key': 'Lux',
   'name': 'Lux'},
  '101': {'title': 'the Magus Ascendant',
   'id': 101,
   'key': 'Xerath',
   'name': 'Xerath'},
  '102': {'title': 'the Half-Dragon',
   'id': 102,
   'key': 'Shyvana',
   'name': 'Shyvana'},
  '103': {'title': 'the Nine-Tailed Fox',
   'id': 103,
   'key': 'Ahri',
   'name': 'Ahri'},
  '104': {'title': 'the Outlaw', 'id': 104, 'key': 'Graves', 'name': 'Graves'},
  '105': {'title': 'the Tidal Trickster',
   'id': 105,
   'key': 'Fizz',
   'name': 'Fizz'},
  '106': {'title': "the Thunder's Roar",
   'id': 106,
   'key': 'Volibear',
   'name': 'Volibear'},
  '107': {'title': 'the Pridestalker',
   'id': 107,
   'key': 'Rengar',
   'name': 'Rengar'},
  '110': {'title': 'the Arrow of Retribution',
   'id': 110,
   'key': 'Varus',
   'name': 'Varus'},
  '111': {'title': 'the Titan of the Depths',
   'id': 111,
   'key': 'Nautilus',
   'name': 'Nautilus'},
  '112': {'title': 'the Machine Herald',
   'id': 112,
   'key': 'Viktor',
   'name': 'Viktor'},
  '113': {'title': 'Fury of the North',
   'id': 113,
   'key': 'Sejuani',
   'name': 'Sejuani'},
  '114': {'title': 'the Grand Duelist',
   'id': 114,
   'key': 'Fiora',
   'name': 'Fiora'},
  '115': {'title': 'the Hexplosives Expert',
   'id': 115,
   'key': 'Ziggs',
   'name': 'Ziggs'},
  '117': {'title': 'the Fae Sorceress',
   'id': 117,
   'key': 'Lulu',
   'name': 'Lulu'},
  '119': {'title': 'the Glorious Executioner',
   'id': 119,
   'key': 'Draven',
   'name': 'Draven'},
  '120': {'title': 'the Shadow of War',
   'id': 120,
   'key': 'Hecarim',
   'name': 'Hecarim'},
  '121': {'title': 'the Voidreaver',
   'id': 121,
   'key': 'Khazix',
   'name': "Kha'Zix"},
  '122': {'title': 'the Hand of Noxus',
   'id': 122,
   'key': 'Darius',
   'name': 'Darius'},
  '126': {'title': 'the Defender of Tomorrow',
   'id': 126,
   'key': 'Jayce',
   'name': 'Jayce'},
  '127': {'title': 'the Ice Witch',
   'id': 127,
   'key': 'Lissandra',
   'name': 'Lissandra'},
  '131': {'title': 'Scorn of the Moon',
   'id': 131,
   'key': 'Diana',
   'name': 'Diana'},
  '133': {'title': "Demacia's Wings",
   'id': 133,
   'key': 'Quinn',
   'name': 'Quinn'},
  '134': {'title': 'the Dark Sovereign',
   'id': 134,
   'key': 'Syndra',
   'name': 'Syndra'},
  '136': {'title': 'The Star Forger',
   'id': 136,
   'key': 'AurelionSol',
   'name': 'Aurelion Sol'},
  '141': {'title': 'the Shadow Reaper',
   'id': 141,
   'key': 'Kayn',
   'name': 'Kayn'},
  '143': {'title': 'Rise of the Thorns',
   'id': 143,
   'key': 'Zyra',
   'name': 'Zyra'},
  '150': {'title': 'the Missing Link',
   'id': 150,
   'key': 'Gnar',
   'name': 'Gnar'},
  '154': {'title': 'the Secret Weapon',
   'id': 154,
   'key': 'Zac',
   'name': 'Zac'},
  '157': {'title': 'the Unforgiven',
   'id': 157,
   'key': 'Yasuo',
   'name': 'Yasuo'},
  '161': {'title': 'the Eye of the Void',
   'id': 161,
   'key': 'Velkoz',
   'name': "Vel'Koz"},
  '163': {'title': 'the Stoneweaver',
   'id': 163,
   'key': 'Taliyah',
   'name': 'Taliyah'},
  '164': {'title': 'the Steel Shadow',
   'id': 164,
   'key': 'Camille',
   'name': 'Camille'},
  '201': {'title': 'the Heart of the Freljord',
   'id': 201,
   'key': 'Braum',
   'name': 'Braum'},
  '202': {'title': 'the Virtuoso', 'id': 202, 'key': 'Jhin', 'name': 'Jhin'},
  '203': {'title': 'The Eternal Hunters',
   'id': 203,
   'key': 'Kindred',
   'name': 'Kindred'},
  '222': {'title': 'the Loose Cannon',
   'id': 222,
   'key': 'Jinx',
   'name': 'Jinx'},
  '223': {'title': 'the River King',
   'id': 223,
   'key': 'TahmKench',
   'name': 'Tahm Kench'},
  '236': {'title': 'the Purifier',
   'id': 236,
   'key': 'Lucian',
   'name': 'Lucian'},
  '238': {'title': 'the Master of Shadows',
   'id': 238,
   'key': 'Zed',
   'name': 'Zed'},
  '240': {'title': 'the Cantankerous Cavalier',
   'id': 240,
   'key': 'Kled',
   'name': 'Kled'},
  '245': {'title': 'the Boy Who Shattered Time',
   'id': 245,
   'key': 'Ekko',
   'name': 'Ekko'},
  '254': {'title': 'the Piltover Enforcer',
   'id': 254,
   'key': 'Vi',
   'name': 'Vi'},
  '266': {'title': 'the Darkin Blade',
   'id': 266,
   'key': 'Aatrox',
   'name': 'Aatrox'},
  '267': {'title': 'the Tidecaller', 'id': 267, 'key': 'Nami', 'name': 'Nami'},
  '268': {'title': 'the Emperor of the Sands',
   'id': 268,
   'key': 'Azir',
   'name': 'Azir'},
  '412': {'title': 'the Chain Warden',
   'id': 412,
   'key': 'Thresh',
   'name': 'Thresh'},
  '420': {'title': 'the Kraken Priestess',
   'id': 420,
   'key': 'Illaoi',
   'name': 'Illaoi'},
  '421': {'title': 'the Void Burrower',
   'id': 421,
   'key': 'RekSai',
   'name': "Rek'Sai"},
  '427': {'title': 'the Green Father',
   'id': 427,
   'key': 'Ivern',
   'name': 'Ivern'},
  '429': {'title': 'the Spear of Vengeance',
   'id': 429,
   'key': 'Kalista',
   'name': 'Kalista'},
  '432': {'title': 'the Wandering Caretaker',
   'id': 432,
   'key': 'Bard',
   'name': 'Bard'},
  '497': {'title': 'The Charmer', 'id': 497, 'key': 'Rakan', 'name': 'Rakan'},
  '498': {'title': 'the Rebel', 'id': 498, 'key': 'Xayah', 'name': 'Xayah'},
  '516': {'title': 'The Fire below the Mountain',
   'id': 516,
   'key': 'Ornn',
   'name': 'Ornn'}}}

now we have another dictionary and unique id's for all.

In [8]:
df['t1_champ1'] = df['t1_champ1id'].apply(lambda x: champ_data['data'][str(x)]['name'])
df['t1_champ2'] = df['t1_champ2id'].apply(lambda x: champ_data['data'][str(x)]['name'])
df['t1_champ3'] = df['t1_champ3id'].apply(lambda x: champ_data['data'][str(x)]['name'])
df['t1_champ4'] = df['t1_champ4id'].apply(lambda x: champ_data['data'][str(x)]['name'])
df['t1_champ5'] = df['t1_champ5id'].apply(lambda x: champ_data['data'][str(x)]['name'])

df['t2_champ1'] = df['t2_champ1id'].apply(lambda x: champ_data['data'][str(x)]['name'])
df['t2_champ2'] = df['t2_champ2id'].apply(lambda x: champ_data['data'][str(x)]['name'])
df['t2_champ3'] = df['t2_champ3id'].apply(lambda x: champ_data['data'][str(x)]['name'])
df['t2_champ4'] = df['t2_champ4id'].apply(lambda x: champ_data['data'][str(x)]['name'])
df['t2_champ5'] = df['t2_champ5id'].apply(lambda x: champ_data['data'][str(x)]['name'])

In [9]:
df

,gameId,creationTime,gameDuration,seasonId,winner,firstBlood,firstTower,firstInhibitor,firstBaron,firstDragon,...,t1_champ1,t1_champ2,t1_champ3,t1_champ4,t1_champ5,t2_champ1,t2_champ2,t2_champ3,t2_champ4,t2_champ5
0,3326086514,1504279457970,1949,9,1,2,1,1,1,1,...,Vladimir,Bard,Kog'Maw,Master Yi,Viktor,Graves,Xayah,Darius,Zed,Thresh
1,3229566029,1497848803862,1851,9,1,1,1,1,0,1,...,Draven,Irelia,Nidalee,Kayle,Shaco,Malphite,Morgana,Hecarim,Yasuo,Riven
2,3327363504,1504360103310,1493,9,1,2,1,1,1,2,...,Tristana,Kayn,Nami,Rumble,Kassadin,Cassiopeia,Thresh,Jayce,Jax,Ashe
3,3326856598,1504348503996,1758,9,1,1,1,1,1,1,...,Maokai,Brand,Twitch,Orianna,Dr. Mundo,Malzahar,Warwick,Thresh,Riven,Ashe
4,3330080762,1504554410899,2094,9,1,2,1,1,1,1,...,Warwick,Twitch,Janna,Draven,Syndra,Sona,Jarvan IV,Kayn,Kassadin,Caitlyn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51485,3308904636,1503076540231,1944,9,2,1,2,2,0,2,...,Warwick,Kalista,Talon,Bard,Lee Sin,Veigar,Yorick,Vayne,Janna,Gragas
51486,3215685759,1496957179355,3304,9,2,1,1,2,2,2,...,Malzahar,Amumu,Cho'Gath,Thresh,Tristana,Shyvana,Kalista,Leona,Nasus,Veigar
51487,3322765040,1504029863961,2156,9,2,2,2,2,0,1,...,Kayn,Tristana,Bard,Ezreal,Rumble,Annie,Draven,Rammus,Karma,Lux
51488,3256675373,1499562036246,1475,9,2,2,2,2,0,2,...,Kha'Zix,Lucian,Illaoi,Braum,Lux,Miss Fortune,Nocturne,Morgana,Karthus,Master Yi
51489,3317333020,1503612754059,1445,9,1,1,1,1,1,2,...,Leona,Annie,Camille,Sejuani,Jhin,Brand,Teemo,Twitch,Kha'Zix,Renekton

now we converted champID's into a their name. we can look for a corelation between them.

In [10]:
df = df[['t1_champ1', 't1_champ2', 't1_champ3', 't1_champ4', 't1_champ5', 't2_champ1', 't2_champ2', 't2_champ3', 't2_champ4', 't2_champ5', 'firstBlood', 'firstDragon', 'firstTower', 'winner']]

In [11]:
df

,t1_champ1,t1_champ2,t1_champ3,t1_champ4,t1_champ5,t2_champ1,t2_champ2,t2_champ3,t2_champ4,t2_champ5,firstBlood,firstDragon,firstTower,winner
0,Vladimir,Bard,Kog'Maw,Master Yi,Viktor,Graves,Xayah,Darius,Zed,Thresh,2,1,1,1
1,Draven,Irelia,Nidalee,Kayle,Shaco,Malphite,Morgana,Hecarim,Yasuo,Riven,1,1,1,1
2,Tristana,Kayn,Nami,Rumble,Kassadin,Cassiopeia,Thresh,Jayce,Jax,Ashe,2,2,1,1
3,Maokai,Brand,Twitch,Orianna,Dr. Mundo,Malzahar,Warwick,Thresh,Riven,Ashe,1,1,1,1
4,Warwick,Twitch,Janna,Draven,Syndra,Sona,Jarvan IV,Kayn,Kassadin,Caitlyn,2,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51485,Warwick,Kalista,Talon,Bard,Lee Sin,Veigar,Yorick,Vayne,Janna,Gragas,1,2,2,2
51486,Malzahar,Amumu,Cho'Gath,Thresh,Tristana,Shyvana,Kalista,Leona,Nasus,Veigar,1,2,1,2
51487,Kayn,Tristana,Bard,Ezreal,Rumble,Annie,Draven,Rammus,Karma,Lux,2,1,2,2
51488,Kha'Zix,Lucian,Illaoi,Braum,Lux,Miss Fortune,Nocturne,Morgana,Karthus,Master Yi,2,2,2,2
51489,Leona,Annie,Camille,Sejuani,Jhin,Brand,Teemo,Twitch,Kha'Zix,Renekton,1,2,1,1

now we have a combination of matches with just champions names and an additionally 'winner' column. 

but again these are not values that we can fit the model with. we will convert them to binary and our model will use them correctly. 

and there shouldn't be a corealation about champions picking order. champ1 or champ2 pick's shouldn't be matter.

## one hot encoding

In [12]:
pd.get_dummies(df['t1_champ1'])

,Aatrox,Ahri,Akali,Alistar,Amumu,Anivia,Annie,Ashe,Aurelion Sol,Azir,...,Xayah,Xerath,Xin Zhao,Yasuo,Yorick,Zac,Zed,Ziggs,Zilean,Zyra
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51485,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
51486,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
51487,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
51488,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
51489,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [13]:
pd.get_dummies(df['t1_champ1'], prefix='t1').astype(int)

,t1_Aatrox,t1_Ahri,t1_Akali,t1_Alistar,t1_Amumu,t1_Anivia,t1_Annie,t1_Ashe,t1_Aurelion Sol,t1_Azir,...,t1_Xayah,t1_Xerath,t1_Xin Zhao,t1_Yasuo,t1_Yorick,t1_Zac,t1_Zed,t1_Ziggs,t1_Zilean,t1_Zyra
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51485,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
51486,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
51487,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
51488,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
51489,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [14]:
# Remove the extra closing parenthesis
encodings1 = [pd.get_dummies(df[col], prefix='t1') for col in ['t1_champ1', 't1_champ2', 't1_champ3', 't1_champ4', 't1_champ5']]

combined_df1 = sum(encodings1)

encodings2 = [pd.get_dummies(df[col], prefix='t2') for col in ['t2_champ1', 't2_champ2', 't2_champ3', 't2_champ4', 't2_champ5']]

combined_df2 = sum(encodings2)

In [15]:
combined_df1

,t1_Aatrox,t1_Ahri,t1_Akali,t1_Alistar,t1_Amumu,t1_Anivia,t1_Annie,t1_Ashe,t1_Aurelion Sol,t1_Azir,...,t1_Xayah,t1_Xerath,t1_Xin Zhao,t1_Yasuo,t1_Yorick,t1_Zac,t1_Zed,t1_Ziggs,t1_Zilean,t1_Zyra
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51485,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
51486,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
51487,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
51488,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
51489,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [16]:
combined_df2

,t2_Aatrox,t2_Ahri,t2_Akali,t2_Alistar,t2_Amumu,t2_Anivia,t2_Annie,t2_Ashe,t2_Aurelion Sol,t2_Azir,...,t2_Xayah,t2_Xerath,t2_Xin Zhao,t2_Yasuo,t2_Yorick,t2_Zac,t2_Zed,t2_Ziggs,t2_Zilean,t2_Zyra
0,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,1,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
2,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51485,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
51486,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
51487,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
51488,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
51489,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [17]:
df = df.join(combined_df1).join(combined_df2)

In [18]:
df

,t1_champ1,t1_champ2,t1_champ3,t1_champ4,t1_champ5,t2_champ1,t2_champ2,t2_champ3,t2_champ4,t2_champ5,...,t2_Xayah,t2_Xerath,t2_Xin Zhao,t2_Yasuo,t2_Yorick,t2_Zac,t2_Zed,t2_Ziggs,t2_Zilean,t2_Zyra
0,Vladimir,Bard,Kog'Maw,Master Yi,Viktor,Graves,Xayah,Darius,Zed,Thresh,...,1,0,0,0,0,0,1,0,0,0
1,Draven,Irelia,Nidalee,Kayle,Shaco,Malphite,Morgana,Hecarim,Yasuo,Riven,...,0,0,0,1,0,0,0,0,0,0
2,Tristana,Kayn,Nami,Rumble,Kassadin,Cassiopeia,Thresh,Jayce,Jax,Ashe,...,0,0,0,0,0,0,0,0,0,0
3,Maokai,Brand,Twitch,Orianna,Dr. Mundo,Malzahar,Warwick,Thresh,Riven,Ashe,...,0,0,0,0,0,0,0,0,0,0
4,Warwick,Twitch,Janna,Draven,Syndra,Sona,Jarvan IV,Kayn,Kassadin,Caitlyn,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51485,Warwick,Kalista,Talon,Bard,Lee Sin,Veigar,Yorick,Vayne,Janna,Gragas,...,0,0,0,0,1,0,0,0,0,0
51486,Malzahar,Amumu,Cho'Gath,Thresh,Tristana,Shyvana,Kalista,Leona,Nasus,Veigar,...,0,0,0,0,0,0,0,0,0,0
51487,Kayn,Tristana,Bard,Ezreal,Rumble,Annie,Draven,Rammus,Karma,Lux,...,0,0,0,0,0,0,0,0,0,0
51488,Kha'Zix,Lucian,Illaoi,Braum,Lux,Miss Fortune,Nocturne,Morgana,Karthus,Master Yi,...,0,0,0,0,0,0,0,0,0,0
51489,Leona,Annie,Camille,Sejuani,Jhin,Brand,Teemo,Twitch,Kha'Zix,Renekton,...,0,0,0,0,0,0,0,0,0,0

As you can see, we have combined our latest dataframe with many operations we did above.

and now we can drop the columns with champion names because we won't use them we don't need them

In [19]:
df = df.drop(['t1_champ1', 't1_champ2', 't1_champ3', 't1_champ4', 't1_champ5', 't2_champ1', 't2_champ2', 't2_champ3', 't2_champ4', 't2_champ5'], axis=1)

In [20]:
df

,firstBlood,firstDragon,firstTower,winner,t1_Aatrox,t1_Ahri,t1_Akali,t1_Alistar,t1_Amumu,t1_Anivia,...,t2_Xayah,t2_Xerath,t2_Xin Zhao,t2_Yasuo,t2_Yorick,t2_Zac,t2_Zed,t2_Ziggs,t2_Zilean,t2_Zyra
0,2,1,1,1,0,0,0,0,0,0,...,1,0,0,0,0,0,1,0,0,0
1,1,1,1,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
2,2,2,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51485,1,2,2,2,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
51486,1,2,1,2,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
51487,2,1,2,2,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
51488,2,2,2,2,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
51489,1,2,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

## model selection

In [21]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

In [22]:
X, y = df.drop('winner', axis=1), df['winner']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15)

Since the model we have chosen does not have scale sensitivity, we will start modeling directly without doing any processing on our data.

In [23]:
clf = RandomForestClassifier(n_jobs=-1) 

clf.fit(X_train, y_train)

# n_jobs=-1 maximizes the computational resources available
# on your machine, making the training process 
# faster if your system has multiple cores.

RandomForestClassifier(n_jobs=-1)

In [24]:
clf.score(X_test, y_test)

0.7187985499741066

![](scoreWout'firstBlood'.png)

As you can see, our score is 0.53. This may be a low score compared to other machine learning projects, but it is actually a reasonable score for the leauge of legends. If you look at game-related sites, the winning rate of any champion among all matches is around 55 to 60, and this rate is the maximum rate.

but along with these, we can add other things to our project, such as who can take the first tower or which champion can it be? which champion can kill the first dragon? extra things can be added.

for example, for the first blood, we go to the code on line 10 and add an extra first blood column. and rerunning the code.

After adding an extra firstBlood column our score went from 53 to 57

![](scoreWith'firstBlood'.png)

now we will add an extra first Dragon column and look at our score

![](latestScore.png)

as you can see, after adding new important columns related to the match, our score increases significantly.

In [25]:
importances = dict(zip(clf.feature_names_in_, clf.feature_importances_))
sorted_importances = sorted(importances.items(), key=lambda x: x[1], reverse=True)

In [26]:
sorted_importances

[('firstTower', 0.10986039334982661),
 ('firstDragon', 0.08316151383956427),
 ('firstBlood', 0.020274032506780632),
 ('t1_Tristana', 0.00602559489121859),
 ('t2_Tristana', 0.005783830452406727),
 ('t2_Thresh', 0.005545717240797084),
 ('t1_Kayn', 0.005475552827365988),
 ('t1_Vayne', 0.005375221661112429),
 ('t2_Kayn', 0.005312563787340166),
 ('t2_Vayne', 0.005195522261643243),
 ('t1_Thresh', 0.00508002519617016),
 ('t1_Yasuo', 0.005073984268767159),
 ('t2_Yasuo', 0.005043497094531747),
 ('t1_Lux', 0.004790081084003789),
 ('t1_Xayah', 0.00469334127022827),
 ('t2_Lux', 0.004675050965998566),
 ('t2_Gragas', 0.004661521001753157),
 ('t1_Jhin', 0.0046414195564316195),
 ('t1_Jinx', 0.004608208126882069),
 ('t2_Jax', 0.004597185701582823),
 ('t2_Lucian', 0.004597013961640625),
 ('t1_Lucian', 0.004528445817954728),
 ('t1_Gragas', 0.004522067188769298),
 ('t2_Xayah', 0.004516949491288477),
 ('t2_Jinx', 0.004463436202819854),
 ('t1_Jax', 0.0044634261359262385),
 ('t2_Orianna', 0.004443442863989406),
 ('t2_Jhin', 0.004414315563694724),
 ('t2_Zed', 0.004351877594568666),
 ('t1_Zed', 0.004329225960049621),
 ('t1_Orianna', 0.004328654853402398),
 ('t1_Ahri', 0.004279329562377556),
 ('t1_Lulu', 0.0042733026328747765),
 ('t2_Blitzcrank', 0.004270497433801883),
 ('t2_Riven', 0.004262970420133777),
 ('t1_Janna', 0.004254844669895918),
 ('t2_Ahri', 0.00422891318019106),
 ('t2_Twitch', 0.004220729371842026),
 ('t2_Lulu', 0.004200006299932556),
 ('t2_Lee Sin', 0.004179103571271159),
 ('t1_Twitch', 0.004175497857933037),
 ('t1_Master Yi', 0.004175028892027522),
 ('t2_Jarvan IV', 0.004170239093438367),
 ('t2_Rakan', 0.004141164392465053),
 ('t2_Warwick', 0.004140593249916435),
 ('t1_Blitzcrank', 0.0041316345700952205),
 ('t1_Caitlyn', 0.004116350049528989),
 ('t2_Master Yi', 0.004089828285912822),
 ('t1_Riven', 0.004086824548843527),
 ('t1_Lee Sin', 0.004049849498041215),
 ('t1_Rakan', 0.004039291433027608),
 ('t1_Miss Fortune', 0.003995870713537358),
 ('t2_Janna', 0.003991994835345435),
 ('t1_Warwick', 0.003949244253984841),
 ('t2_Caitlyn', 0.003918776265043821),
 ('t1_Jarvan IV', 0.003917621351650433),
 ('t2_Morgana', 0.0038887047343318824),
 ('t1_Soraka', 0.0038862471788570865),
 ('t1_Morgana', 0.0038855554042588106),
 ('t2_Miss Fortune', 0.0037486634773002013),
 ('t2_Ekko', 0.0037244195510833127),
 ('t2_Ezreal', 0.003723371896359062),
 ('t1_Ezreal', 0.0037068575302892357),
 ('t1_Draven', 0.0036640161881089373),
 ('t1_Ashe', 0.003636310646081334),
 ('t1_Nasus', 0.003632665613423469),
 ('t1_Ekko', 0.0036233127448435146),
 ('t2_Gangplank', 0.003594201718249329),
 ('t2_Ashe', 0.003578716284924186),
 ('t2_Draven', 0.0035667598172943443),
 ('t1_Maokai', 0.0035556532672456286),
 ('t2_Sona', 0.0035318954254094075),
 ('t1_Leona', 0.0035072623469170243),
 ('t2_Maokai', 0.003437112191195624),
 ('t2_Renekton', 0.003419563105238584),
 ('t2_Nami', 0.003411882070611809),
 ('t1_Veigar', 0.0034022669850640582),
 ('t2_Leona', 0.003396924196401286),
 ('t2_Nasus', 0.0033941949540285715),
 ("t1_Kha'Zix", 0.0033720149277533316),
 ('t1_Teemo', 0.003366306931690529),
 ('t2_Soraka', 0.003349846639490596),
 ("t1_Cho'Gath", 0.003345162643121333),
 ('t1_Brand', 0.0033056780381573287),
 ('t2_Gnar', 0.003305168834873073),
 ('t1_Sona', 0.00329893965926602),
 ("t2_Cho'Gath", 0.0032867643289063823),
 ('t2_Veigar', 0.0032815798877815377),
 ('t1_Gangplank', 0.0032787208160703555),
 ('t1_Malzahar', 0.0032645303708590777),
 ('t1_Renekton', 0.003263678938018909),
 ('t2_Teemo', 0.0032596716147131537),
 ('t2_Tryndamere', 0.0032546688374031855),
 ('t1_Darius', 0.003239662126703413),
 ('t1_Nami', 0.0032389307691694283),
 ('t1_Ornn', 0.0032341308758099875),
 ('t2_Garen', 0.003195219378160191),
 ('t1_Garen', 0.003180183673757032),
 ('t2_Twisted Fate', 0.003173851120458913),
 ("t2_Kha'Zix", 0.003168826100064182),
 ('t2_Sivir', 0.0031619825828798714),
 ('t2_Darius', 0.003151682436816645),
 ('t1_Sejuani', 0.0031215817372283543),
 ('t2_Brand', 0.003108861260250392),
 ('t2_Malzahar', 0.003104090770111012),
 ('t1_Gnar', 0.0031039281776594468),
 ('t1_Talon', 0.0030963964890234107),
 ('t2_Ornn', 0.0030425797398092353),
 ('t2_Bard', 0.0030424621285779),
 ('t2_Braum', 0.003042077225379714),
 ('t1_Sivir', 0.0030401506751878554),
 ('t1_Fizz', 0.0030237845453236303),
 ('t2_Shen', 0.003021487894063278),
 ('t1_Twisted Fate', 0.0030141811799505934),
 ('t1_Shen', 0.003005841255870078),
 ('t2_Jayce', 0.0030019274241719117),
 ('t1_Tryndamere', 0.0029898356977840906),
 ('t1_Bard', 0.002971854873672825),
 ('t2_Annie', 0.0029454686911813913),
 ('t2_Sejuani', 0.002945259536644578),
 ("t1_Kog'Maw", 0.002941626033215986),
 ('t1_Xin Zhao', 0.0029395347016631505),
 ('t2_Katarina', 0.0029320137205993044),
 ('t1_Fiora', 0.0029214580646543557),
 ('t2_Kalista', 0.0029207680723529438),
 ('t1_Jayce', 0.0029200958448068652),
 ('t2_Talon', 0.0028924489465819297),
 ("t1_Vel'Koz", 0.0028919063313547896),
 ('t1_Syndra', 0.0028897605804039527),
 ('t2_Alistar', 0.0028831206541813934),
 ('t1_Braum', 0.002877953884839296),
 ('t1_Vladimir', 0.0028712829974082677),
 ('t2_Rammus', 0.0028686029340932043),
 ('t1_Katarina', 0.002857369798184795),
 ('t1_Cassiopeia', 0.0028498473306470193),
 ("t2_Kog'Maw", 0.0028417961339310903),
 ('t2_Akali', 0.0028297407901994257),
 ('t1_Vi', 0.0028216626426690156),
 ('t1_Alistar', 0.0028194087838750606),
 ('t2_Fizz', 0.00281715567887593),
 ('t2_Diana', 0.0028072036146992124),
 ('t2_Malphite', 0.002800000207257684),
 ('t1_Karma', 0.0027837395059675677),
 ('t1_Annie', 0.002776898602145308),
 ("t2_Vel'Koz", 0.0027516034303102215),
 ('t2_Kassadin', 0.0027355556375356013),
 ('t2_Syndra', 0.0027298694872578974),
 ('t1_Kalista', 0.0027240604825219954),
 ('t1_Diana', 0.002708802745557434),
 ('t2_Vladimir', 0.002706884822428042),
 ('t2_Xin Zhao', 0.0026791831331006016),
 ('t1_Kassadin', 0.0026750655903159384),
 ('t1_Rammus', 0.002673897764656588),
 ('t1_Akali', 0.002655074992071954),
 ('t2_Fiora', 0.0026458658316341624),
 ('t1_Pantheon', 0.002633869412561052),
 ('t2_Vi', 0.0026307083406405577),
 ('t2_Galio', 0.0026277127025245406),
 ('t2_Corki', 0.0025516224649731528),
 ('t2_Cassiopeia', 0.0025411648278814308),
 ('t1_Shaco', 0.0025356021214751334),
 ('t1_Ziggs', 0.002528330394622051),
 ('t1_Galio', 0.002497899717409773),
 ('t2_Shaco', 0.002495672868249078),
 ('t1_Elise', 0.002473362532685356),
 ('t2_Shyvana', 0.0024655287021403405),
 ('t2_Pantheon', 0.0024596436387644164),
 ('t2_Taric', 0.002453132232777708),
 ('t2_Elise', 0.0024475611731982483),
 ('t1_Varus', 0.0024352325231451586),
 ('t1_Taric', 0.0024301909658709757),
 ('t1_Malphite', 0.0024253411342752616),
 ('t2_Urgot', 0.0024043141239745197),
 ('t2_Anivia', 0.0023995847085341434),
 ('t1_Irelia', 0.0023984084728230497),
 ('t1_Zac', 0.0023982468580844942),
 ('t1_Shyvana', 0.002389521698382214),
 ('t1_Anivia', 0.0023785373879529575),
 ('t1_Corki', 0.002357739951964023),
 ('t2_Karma', 0.0023551077717198932),
 ('t2_Sion', 0.0023525519463316333),
 ('t2_Irelia', 0.0023445738051080336),
 ('t2_Amumu', 0.002332895897758242),
 ('t2_Zyra', 0.0023185272259273033),
 ('t2_Trundle', 0.0023130174260590003),
 ('t2_Varus', 0.002310279651150281),
 ('t2_Zac', 0.0022914126509610594),
 ('t1_Sion', 0.0022655182563124238),
 ('t2_Rengar', 0.002256628945625781),
 ('t2_Wukong', 0.0022486143106346737),
 ('t1_LeBlanc', 0.002232622579375551),
 ('t1_Kayle', 0.002214402102817596),
 ('t2_LeBlanc', 0.0022127588715516525),
 ('t1_Wukong', 0.002190861412145548),
 ('t1_Amumu', 0.0021753017488481386),
 ('t2_Ziggs', 0.0021327026281293075),
 ('t1_Zyra', 0.0021318277407268546),
 ('t1_Kennen', 0.0021106634764574026),
 ('t2_Camille', 0.0020800954748961898),
 ('t2_Kayle', 0.002078682646302956),
 ('t1_Camille', 0.0020670556681201277),
 ('t2_Viktor', 0.0020616319429561172),
 ('t1_Rengar', 0.0020587718071215636),
 ('t1_Hecarim', 0.0020523184922307276),
 ('t1_Trundle', 0.0020474680405818146),
 ('t1_Urgot', 0.002046762605438979),
 ('t1_Viktor', 0.002018062487510528),
 ('t2_Poppy', 0.0020148636878394646),
 ('t1_Poppy', 0.0019894974667555286),
 ('t2_Nautilus', 0.0019875295489538204),
 ('t1_Nautilus', 0.001980392442422269),
 ('t1_Heimerdinger', 0.0019575404890887303),
 ('t2_Xerath', 0.0019532797760132507),
 ('t2_Fiddlesticks', 0.0019480246292413455),
 ('t2_Hecarim', 0.0019468282961118224),
 ('t1_Xerath', 0.0019217232686110095),
 ('t2_Taliyah', 0.0019209644388622166),
 ('t1_Fiddlesticks', 0.001917446148252124),
 ('t1_Kled', 0.0019174272745008558),
 ('t2_Kennen', 0.0019134675379949026),
 ('t1_Taliyah', 0.0018969964267041754),
 ('t2_Dr. Mundo', 0.0018831063196271891),
 ('t2_Kled', 0.001881231729276632),
 ('t1_Rumble', 0.0018439467812013156),
 ('t1_Graves', 0.0018371779413028835),
 ('t2_Tahm Kench', 0.0018332775594978089),
 ('t2_Evelynn', 0.001826190952949224),
 ('t1_Nocturne', 0.001808197512474351),
 ('t1_Nidalee', 0.0018030886197606762),
 ('t2_Olaf', 0.001802003328147849),
 ('t2_Graves', 0.0017981600003188266),
 ('t2_Nocturne', 0.0017944538556905279),
 ('t1_Dr. Mundo', 0.0017734031654765602),
 ('t1_Swain', 0.0017719123522731283),
 ('t2_Swain', 0.0017507881119158055),
 ('t2_Nidalee', 0.0017369180124791439),
 ('t1_Yorick', 0.0017292499988063594),
 ('t2_Heimerdinger', 0.0017236914737136985),
 ('t1_Illaoi', 0.0017195377554182394),
 ('t1_Olaf', 0.0017024817178223513),
 ('t2_Illaoi', 0.001701459517248409),
 ('t2_Rumble', 0.0016895877502209635),
 ('t1_Evelynn', 0.0016561362467366742),
 ("t1_Rek'Sai", 0.0016471154532262916),
 ('t2_Singed', 0.0016305759833433395),
 ('t1_Tahm Kench', 0.001616796684578039),
 ('t1_Zilean', 0.0016127757049095928),
 ('t1_Singed', 0.0016109183803489889),
 ('t2_Volibear', 0.0015715449189893252),
 ('t1_Kindred', 0.0015531643550521005),
 ('t2_Zilean', 0.0015432904456575526),
 ('t1_Nunu', 0.0015125614127910513),
 ('t2_Azir', 0.0014953350134902226),
 ('t2_Yorick', 0.001490388557571679),
 ('t1_Mordekaiser', 0.0014842087974158624),
 ('t1_Udyr', 0.0014714874021721476),
 ('t2_Quinn', 0.0014604698369427144),
 ('t1_Quinn', 0.001457150488951408),
 ('t2_Nunu', 0.0014481742338535225),
 ('t1_Azir', 0.0014334468485760034),
 ('t2_Lissandra', 0.0014311616558030664),
 ('t1_Lissandra', 0.0014287787921844436),
 ('t2_Udyr', 0.0014274404712507746),
 ('t2_Mordekaiser', 0.0014217865739247608),
 ("t2_Rek'Sai", 0.0014141060202958217),
 ('t2_Ivern', 0.001413546615794774),
 ('t2_Karthus', 0.0013984981931816393),
 ('t1_Volibear', 0.0013823644842700235),
 ('t1_Ivern', 0.0013595784597896642),
 ('t1_Ryze', 0.0013317440023553836),
 ('t2_Kindred', 0.0013119627179598733),
 ('t2_Ryze', 0.0012743512383277574),
 ('t1_Aurelion Sol', 0.0011445970154391803),
 ('t1_Karthus', 0.0011355960585285106),
 ('t2_Aurelion Sol', 0.0011302813039117353),
 ('t1_Aatrox', 0.0011279345791520153),
 ('t2_Aatrox', 0.0011208729913495465),
 ('t2_Skarner', 0.0008717232564928136),
 ('t1_Skarner', 0.000792835265749053)]

as you can see, the team that takes the first tower, kills the first dragon, sheds the first blood or first chooses the champion named Tristana has a higher chance of winning.